[INJIMOB-1226] add cbor decode functionality
mosip/pixelpass-ios-swift pull request #4
Opened 2024-06-06 08:27 UTC by abhip2565

2024-06-06 09:30 UTC, Alka1703 commented on Sources/pixelpass/pixelpass.swift
> +                    print("Decoded CBOR data is not a valid JSON object")
Please avoid using print statement. Use os_log which help you add logs in a more structured way. Please refer to tuvali repository for details. Please remove all the print statement from the entire library.

2024-06-06 09:30 UTC, Alka1703 commented on Sources/pixelpass/pixelpass.swift
> +            let byteArray = String(data:decompressedData,encoding: .ascii)?.hexaBytes
`decode` method does 2 task: decompressing and decoding CBOR data. It is good to extract it out into 2 methods and use it.

2024-06-06 09:30 UTC, Alka1703 commented on Sources/pixelpass/Cbor.swift
> +extension CBOR {
YOu can name it better. CBOR is not giving a sense of what is being done. Eg: CBORDecoder

2024-06-06 09:30 UTC, Alka1703 commented on Package.resolved
> +  "version" : 2
Why have we done a version downgrade?

2024-06-06 09:31 UTC, Alka1703 requested changes
Please address the comments

2024-06-06 09:32 UTC, abhip2565 commented on Package.resolved
> +  "version" : 2
To keep the library with same version as inji to avoid version conflicts.

2024-06-06 09:33 UTC, abhip2565 commented on Sources/pixelpass/Cbor.swift
> +extension CBOR {
it is an extension. It should be same as of class name. I dont think it can be changed.

2024-06-06 10:03 UTC, abhip2565 commented on Sources/pixelpass/pixelpass.swift
> +            let byteArray = String(data:decompressedData,encoding: .ascii)?.hexaBytes
This is written the same way kotlin library is written. Can we have a discussion around this?

2024-06-06 10:41 UTC, Alka1703 commented on Sources/pixelpass/Cbor.swift
> +extension CBOR {
In that case, lets try to name the function better.

2024-06-06 10:41 UTC, Alka1703 commented on Sources/pixelpass/pixelpass.swift
> +            let byteArray = String(data:decompressedData,encoding: .ascii)?.hexaBytes
We should think about design and reusability of the code and clean coding practices.

2024-06-06 10:43 UTC, abhip2565 commented on Sources/pixelpass/Cbor.swift
> +extension CBOR {
how about convertToJsonCompatibleFormat?

2024-06-06 10:46 UTC, abhip2565 commented on Sources/pixelpass/pixelpass.swift
> +            let byteArray = String(data:decompressedData,encoding: .ascii)?.hexaBytes
Just thinking, actually It does 3 things. decompression, base45 decode, cbor decode, in that case we would be needing 3 functions.

2024-06-06 10:46 UTC, abhip2565 commented on Sources/pixelpass/pixelpass.swift
> +            let byteArray = String(data:decompressedData,encoding: .ascii)?.hexaBytes
Or separating out only the cbor decode would be a better approach?

2024-06-06 10:49 UTC, Alka1703 commented on Sources/pixelpass/Cbor.swift
> +extension CBOR {
Looks good to me. You should also see the variable name where you have used the function. It should make sense there as well.

2024-06-07 17:24 UTC, swatigoel approved these changes

2024-06-07 17:24 UTC, merged